### ISSUE TITLE
Distinguishing inserts from updates

### ISSUE THREAD

**Issue by markunsworth** [django-nonrel/django#21]
This is possibly mongodb focussed but I don't have enough knowledge of other nonrel dbs to make that call. We're using mongodb so are using djangotoolbox and mongodb-engine.

In the case that another part of our system has modified a document in our collection and our django model isn't totally up to date with the full schema when we save from django we lose the changes made by the other part of the system.

When calling save on a  django model I have discovered that we end up using the `NonrelInsertCompiler` which in most cases isn't really a problem. However in the case that another part of our system has modified the document in our collection and our django model isn't totally up to date with it's schema when we save from django we lose the changes made by the other part of the system. This could also manifest under a simple race condition.

If I was hand writing the db logic, I would be using an update with the `$set` operator to set the fields. I can see that the `NonrelUpdateCompiler` seems to do this, so I figured I could probably use the `force_update` parameter on the `save` call:

```
model.save(force_update=True)
```

but it still ended up doing an insert. So having stepped through the code I can see that the `distinguishes_insert_from_update` is set to False in the `NonrelDatabaseFeatures` class. 

Happy to look into how to get this working. I believe it should work this way, but would like some input/guidance from others first.

**Comment by aburgel** [comment]
Mongodb has some fancier capabilities that are not available in other non-relational databases, so djangotoolbox boils everything down into a set of common operations, which in this case is GET and PUT.

To invoke the NonrelUpdateCompiler, you have to use the update syntax, which is described here:

https://docs.djangoproject.com/en/1.6/topics/db/queries/#updating-multiple-objects-at-once

Otherwise, can you use some sort of transaction, so concurrent updates would be serialized or at least rejected?

**Comment by markunsworth** [comment]
After spending a few days getting my head around how this, djangotoolbox and mongodb-engine fits together, i _think_ I have worked this one out ..... almost.

I'll move this into the mongodb-engine, so you can close this issue out.
